/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdicionarCadastro: typeof import('./src/components/Inventory/Cadastros/AdicionarCadastro.vue')['default']
    BaseTemplateFile: typeof import('./src/components/shared/BaseTemplateFile.vue')['default']
    BreadCrumb: typeof import('./src/components/shared/BreadCrumb.vue')['default']
    CustomInputSelect: typeof import('./src/components/shared/CustomInputSelect.vue')['default']
    EditarCadastro: typeof import('./src/components/Inventory/Cadastros/EditarCadastro.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FormProduto: typeof import('./src/components/Inventory/Produtos/FormProduto.vue')['default']
    FormReceitas: typeof import('./src/components/Inventory/Produtos/FormReceitas.vue')['default']
    FormularioProdutos: typeof import('./src/components/shared/FormularioProdutos.vue')['default']
    FrameProdutos: typeof import('./src/components/Inventory/Produtos/FrameProdutos.vue')['default']
    InfoNoItems: typeof import('./src/components/shared/InfoNoItems.vue')['default']
    InventoryConfiguration: typeof import('./src/components/Inventory/Cadastros/InventoryConfiguration.vue')['default']
    LineChartComponent: typeof import('./src/components/shared/LineChartComponent.vue')['default']
    MenuSuperiorAcoes: typeof import('./src/components/shared/MenuSuperiorAcoes.vue')['default']
    ModalDeCadastro: typeof import('./src/components/Inventory/Cadastros/ModalDeCadastro.vue')['default']
    ModalEvent: typeof import('./src/components/shared/ModalEvent.vue')['default']
    PaginationComponent: typeof import('./src/components/shared/PaginationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableComponent: typeof import('./src/components/shared/TableComponent.vue')['default']
    TableTemplateSkeleton: typeof import('./src/components/shared/TableTemplateSkeleton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
