/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdicionarCadastro: typeof import('./src/components/Inventory/Cadastros/AdicionarCadastro.vue')['default']
    BaseTemplateFile: typeof import('./src/components/shared/BaseTemplateFile.vue')['default']
    BreadCrumb: typeof import('./src/components/shared/BreadCrumb.vue')['default']
    CustomInputSelect: typeof import('./src/components/shared/CustomInputSelect.vue')['default']
    EditarCadastro: typeof import('./src/components/Inventory/Cadastros/EditarCadastro.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FormularioProdutos: typeof import('./src/components/shared/FormularioProdutos.vue')['default']
    FrameProdutos: typeof import('./src/components/Inventory/Produtos/FrameProdutos.vue')['default']
    InfoNoItems: typeof import('./src/components/shared/InfoNoItems.vue')['default']
    InventoryConfiguration: typeof import('./src/components/Inventory/Cadastros/InventoryConfiguration.vue')['default']
    LineChartComponent: typeof import('./src/components/shared/LineChartComponent.vue')['default']
    MenuSuperiorAcoes: typeof import('./src/components/shared/MenuSuperiorAcoes.vue')['default']
    ModalDeCadastro: typeof import('./src/components/Inventory/Cadastros/ModalDeCadastro.vue')['default']
    ModalEvent: typeof import('./src/components/shared/ModalEvent.vue')['default']
    PaginationComponent: typeof import('./src/components/shared/PaginationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableComponent: typeof import('./src/components/shared/TableComponent.vue')['default']
  }
}
